server:
  port: 0
spring :
  jpa:
    hibernate:
       ddl-auto:create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

  application:
    name: CafeInfo-Service

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

pivotal:
  cafeinfoservice:
    name: CafeInfo-Service
  cafereviewservice:
    name: CafeReview-Service